version: "3.8"
services:
    client:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - process.env.PORT
        volumes:
            - "/app/node_modules"
            - "./:/app"